version: "3.7"
networks:
  local:
  traefik:
    external: true
services:
  db:
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$PGDATABASE
    image: postgres:13
    volumes:
      - .db/:/var/lib/postgresql/data
    networks:
      - local
  odoo:
    build: odoo
    environment:
      - DEMO=True
      - MARABUNTA_MODE=demo
      # you can specify your own addons path, if you don't want to use links
      - ADDONS_PATH=/odoo/links,/odoo/local-src,/odoo/src/odoo/addons,/odoo/src/addons,/odoo/external-src/account-payment,/odoo/external-src/account-invoicing,/odoo/external-src/bank-payment,/odoo/external-src/currency,/odoo/external-src/contract,/odoo/external-src/server-tools,/odoo/external-src/server-env,/odoo/external-src/server-ux,/odoo/external-src/stock-logistics-workflow,/odoo/external-src/l10n-brazil,/odoo/external-src/account-financial-reporting,/odoo/external-src/reporting-engine,/odoo/external-src/mis-builder
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`) && PathPrefix(`/longpolling/`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}odoo"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.service=${COMPOSE_PROJECT_NAME}odoo_long"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo.loadbalancer.server.port=8069"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo_long.loadbalancer.server.port=8072"
      - "docky.help=${COMPOSE_PROJECT_NAME}.localhost"
    links:
      - db
    networks:
      - local
      - traefik
