version:  "3.9"
      
services:
  proxy:
    image:  traefik:v2.8
    command:  --api.insecure --providers.docker --providers.docker.exposedbydefault="false"
    ports:
      -  "127.0.0.1:80:80"
      -  "127.0.0.1:8080:8080"
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock
    networks:
      traefik:    
networks:
  traefik:
    name:  traefik